// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "@voidzero-dev/vite-plus-test" {
  export const afterEach: typeof import("bun:test").afterEach;
  export const beforeAll: typeof import("bun:test").beforeAll;
  export const describe: typeof import("bun:test").describe;
  export const expect: typeof import("bun:test").expect;
  export const test: typeof import("bun:test").test;
}
