import { useMemo } from "react";
import type { ActionsContextValue } from "@/hooks/agent-contexts";

export function useAgentProviderActionsAssembly(deps: ActionsContextValue): ActionsContextValue {
  return useMemo(
    () => deps,
    [
      deps.removeProject,
      deps.selectSession,
      deps.loadOlderMessages,
      deps.deleteSession,
      deps.renameSession,
      deps.sendPrompt,
      deps.findFiles,
      deps.sendCommand,
      deps.summarizeSession,
      deps.abortSession,
      deps.respondPermission,
      deps.replyQuestion,
      deps.rejectQuestion,
      deps.setModel,
      deps.setPromptBoxSelection,
      deps.setAgent,
      deps.cycleVariant,
      deps.revertVariant,
      deps.clearError,
      deps.refreshProviders,
      deps.restartHarnesses,
      deps.getQueuedPrompts,
      deps.removeFromQueue,
      deps.reorderQueue,
      deps.updateQueuedPrompt,
      deps.sendQueuedNow,
      deps.setSessionDraft,
      deps.clearSessionDraft,
      deps.openDirectory,
      deps.connectToProject,
      deps.startNewChat,
      deps.setActiveTarget,
      deps.setDefaultChatDirectory,
      deps.setActiveTargetDirectory,
      deps.revertToMessage,
      deps.unrevert,
      deps.forkFromMessage,
      deps.setSessionColor,
      deps.setSessionTags,
      deps.setSessionPinned,
      deps.moveSessionToProject,
      deps.removeSessionFromProject,
      deps.setProjectPinned,
      deps.registerWorktree,
      deps.unregisterWorktree,
      deps.clearWorktreeCleanup,
      deps.createWorkspace,
      deps.updateWorkspace,
      deps.removeWorkspace,
      deps.switchWorkspace,
      deps.reorderWorkspaces,
      deps.reorderVisibleProjects,
    ],
  );
}
