import {
  getActiveWorkspaceId,
  getProjectMetaMap,
  getSessionMetaMap,
  getUnreadSessionIds,
  getWorktreeParents,
} from "@/hooks/agent-state-persistence";
import type { InternalAgentState } from "@/hooks/agent-state-types";
import { getSessionDrafts } from "@/lib/session-drafts";
import type { Workspace } from "@/types/electron";

const initialWorkspaces: Workspace[] = [];

export const initialAgentState: InternalAgentState = {
  workspaces: initialWorkspaces,
  activeWorkspaceId: getActiveWorkspaceId(initialWorkspaces),
  projectWorkspaceMap: {},
  projectHydration: {},
  connections: {},
  sessions: [],
  activeSessionId: null,
  isBusy: false,
  pendingPermissions: {},
  pendingQuestions: {},
  lastError: null,
  sessionErrors: {},
  bootState: "idle",
  bootError: null,
  bootLogs: null,
  workspaceResources: {},
  providers: [],
  providerDefaults: {},
  selectedModel: null,
  busySessionIds: new Set(),
  liveSessionRetainUntil: {},
  agents: [],
  selectedAgent: null,
  variantSelections: {},
  commands: [],
  queuedPrompts: {},
  defaultChatDirectory: null,
  activeTargetDirectory: null,
  activeTargetHarnessId: null,
  namingSessionIds: new Set(),
  unreadSessionIds: getUnreadSessionIds(),
  sessionDrafts: getSessionDrafts(),
  sessionMeta: getSessionMetaMap(),
  projectMeta: getProjectMetaMap(),
  worktreeParents: getWorktreeParents(),
  pendingWorktreeCleanup: null,
  turnRuns: {},
  activeTurnRunBySession: {},
  afterPartPending: new Set(),
  _afterPartTriggered: new Set(),
  _deletedSessionIds: new Set(),
};
